# Generated by Django 4.2.1 on 2023-05-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_product_parent_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
    ]
