# Generated by Django 4.2.1 on 2023-05-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_product_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
    ]
