# Generated by Django 4.2.1 on 2023-05-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_product_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tree_id',
        ),
    ]
